# Generated by Django 6.0 on 2025-12-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
