# Generated by Django 6.0 on 2025-12-30 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_consultation', models.DateField(auto_now_add=True, verbose_name='Date de consultation')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Tension artérielle')),
                ('total_cholesterol', models.FloatField(blank=True, null=True, verbose_name='Cholestérol total')),
                ('ldl', models.FloatField(blank=True, null=True, verbose_name='LDL')),
                ('hdl', models.FloatField(blank=True, null=True, verbose_name='HDL')),
                ('triglycerides', models.FloatField(blank=True, null=True, verbose_name='Triglycérides')),
                ('hba1c', models.FloatField(blank=True, null=True, verbose_name='HbA1c (%)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('nutritional_diagnosis', models.TextField(verbose_name='Diagnostic Nutritionnel (PES)')),
                ('goals', models.TextField(verbose_name='Objectifs nutritionnels')),
                ('intervention_plan', models.TextField(verbose_name="Plan d'intervention")),
                ('next_appointment', models.DateField(blank=True, null=True, verbose_name='Date de suivi')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Petit-déjeuner'), ('snack_am', 'Collation Matin'), ('lunch', 'Déjeuner'), ('snack_pm', 'Collation Après-midi'), ('dinner', 'Dîner')], max_length=20, verbose_name='Moment du repas')),
                ('description', models.TextField(verbose_name="Qu'avez-vous mangé ?")),
                ('beverage', models.BooleanField(default=False, verbose_name='Consommation de boisson sucrée ?')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('1', 'Jour 1'), ('2', 'Jour 2'), ('3', 'Jour 3'), ('4', 'Jour 4'), ('5', 'Jour 5'), ('6', 'Jour 6'), ('7', 'Jour 7')], max_length=1)),
                ('breakfast', models.TextField(verbose_name='Petit-déjeuner')),
                ('morning_snack', models.TextField(blank=True, verbose_name='Collation Matin')),
                ('lunch', models.TextField(verbose_name='Déjeuner')),
                ('afternoon_snack', models.TextField(blank=True, verbose_name='Collation Après-midi')),
                ('dinner', models.TextField(verbose_name='Dîner')),
                ('evening_snack', models.TextField(blank=True, verbose_name='Collation Soir')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('gender', models.CharField(choices=[('Male', 'Homme'), ('Female', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sédentaire'), ('low', 'Faible activité'), ('moderate', 'Activité modérée'), ('intense', 'Activité intense')], max_length=20, verbose_name="Niveau d'activité")),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='Diagnostic')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Date du diagnostic')),
                ('medical_history', models.TextField(blank=True, verbose_name='Antécédents médicaux')),
                ('medications', models.TextField(blank=True, verbose_name='Médicaments')),
                ('allergies', models.BooleanField(default=False, verbose_name='Allergies')),
                ('family_history_cvd', models.BooleanField(default=False, verbose_name='Antécédents familiaux de MCV')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='IMC')),
                ('waist_circumference', models.FloatField(blank=True, null=True, verbose_name='Tour de taille')),
                ('body_fat_percent', models.FloatField(blank=True, null=True, verbose_name='% Masse grasse')),
            ],
        ),
    ]
