# Generated by Django 6.0 on 2025-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='body_fat_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Masse grasse (%)'),
        ),
    ]
