# Generated by Django 6.0 on 2025-12-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_fooddiary_options_fooddiary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['day']},
        ),
        migrations.AlterUniqueTogether(
            name='fooddiary',
            unique_together=set(),
        ),
    ]
