# Generated by Django 6.0 on 2025-12-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_mealplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddiary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fooddiary',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fooddiary',
            name='notes_generales',
        ),
        migrations.RemoveField(
            model_name='fooddiary',
            name='updated_at',
        ),
    ]
