# Generated by Django 6.0 on 2025-12-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_fooddiary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddiary',
            options={'verbose_name': 'Plan alimentaire'},
        ),
    ]
