# Generated by Django 6.0 on 2025-12-30 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_fooddiary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddiary',
            options={'ordering': ['-date'], 'verbose_name': 'Plan alimentaire'},
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Plan actuel'),
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='notes_generales',
            field=models.TextField(blank=True, verbose_name='Instructions globales'),
        ),
        migrations.AddField(
            model_name='fooddiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
